### ISSUE TITLE
investigate peer dependency for webpack

### ISSUE THREAD

**Issue by notmodified** [teamdeeson/deeson-webpack-config#15]
try to avoid silly lookup of webpack

**Comment by johnennewdeeson** [comment]
Webpack should be a dependency of the project not of this module.

**Comment by notmodified** [comment]
i dont think webpack as a peer dependency is the answer.

I think we need to pull the drupal plugin bit out into its own module and deal with it at the same time as https://github.com/teamdeeson/deeson-webpack-config/issues/23.
